# Generated by Django 2.1.1 on 2018-12-14 10:44

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('SerialNumber', models.CharField(default=uuid.uuid4, max_length=10, primary_key=True, serialize=False)),
                ('ProductName', models.CharField(default=None, max_length=100)),
                ('birth_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_creation_time', models.IntegerField()),
                ('history', models.TextField(max_length=300)),
            ],
        ),
    ]
